In [301]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import KFold, cross_val_score

In [302]:
region_one = pd.read_csv('Region_One', delimiter=',')
region_one = region_one.drop(['ID'], axis=1)
region_one

,Abyusif,abram Gad,STUDBME2,BMES_Secrelary,ESP32_One,Saeed,Sbme-Staff,CMP LAB1,CMP LAB2,CMP LAB3,CMP LAB4,CMP_LAB1,CMP_LAB2,CMP_LAB3,CMP_LAB4,Lab-admin,RehabLab,label
0,-100,-100,-55,-76,-81,-100,-100,-69,-68,-69,-67,-55,-56,-55,-55,-76.09,-69.000,1
1,-100,-100,-57,-71,-68,-100,-100,-65,-69,-69,-69,-49,-48,-49,-48,-73.00,-69.000,1
2,-100,-100,-52,-69,-70,-100,-100,-61,-60,-62,-61,-54,-56,-52,-52,-72.00,-66.000,1
3,-100,-100,-54,-72,-69,-100,-100,-60,-63,-62,-100,-44,-45,-42,-41,-76.09,-67.000,1
4,-100,-100,-50,-71,-66,-100,-100,-58,-58,-59,-60,-44,-45,-45,-45,-71.00,-59.000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,-100,-100,-44,-72,-65,-100,-100,-61,-61,-62,-61,-53,-55,-53,-53,-70.00,-62.000,1
496,-100,-100,-44,-71,-67,-100,-100,-60,-59,-60,-59,-58,-58,-58,-59,-71.00,-62.000,1
497,-100,-100,-47,-73,-71,-100,-100,-60,-61,-60,-61,-56,-55,-56,-55,-67.00,-74.944,1
498,-100,-100,-44,-70,-70,-100,-100,-60,-61,-61,-60,-55,-54,-56,-55,-76.09,-62.000,1
499,-100,-100,-52,-71,-65,-100,-100,-60,-59,-59,-60,-58,-59,-57,-57,-70.00,-74.944,1

In [303]:
region_two = pd.read_csv('Region_Two', delimiter=',')
region_two = region_two.drop(['ID'], axis=1)
region_two

,Abyusif,abram Gad,STUDBME2,BMES_Secrelary,ESP32_One,Saeed,Sbme-Staff,CMP LAB1,CMP LAB2,CMP LAB3,CMP LAB4,CMP_LAB1,CMP_LAB2,CMP_LAB3,CMP_LAB4,Lab-admin,RehabLab,label
0,-100,-100,-59,-82,-85,-100,-100,-100,-100,-72,-100,-48,-48,-49,-50,-75.0,-65,2
1,-100,-83,-48,-77,-75,-100,-100,-100,-100,-100,-100,-46,-47,-47,-45,-73.0,-100,2
2,-90,-100,-52,-78,-72,-100,-100,-67,-66,-65,-67,-50,-51,-50,-52,-77.0,-69,2
3,-91,-88,-61,-74,-73,-100,-100,-70,-70,-70,-70,-50,-51,-53,-52,-77.0,-69,2
4,-100,-100,-57,-88,-85,-100,-100,-73,-74,-100,-100,-50,-50,-50,-50,-86.0,-70,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,-100,-100,-47,-70,-68,-100,-100,-60,-60,-60,-61,-47,-48,-47,-46,-66.0,-63,2
392,-86,-100,-46,-80,-68,-100,-100,-62,-63,-63,-64,-50,-45,-46,-46,-66.0,-63,2
393,-89,-83,-44,-68,-66,-100,-100,-66,-68,-68,-68,-49,-49,-49,-49,-63.0,-70,2
394,-100,-100,-49,-82,-71,-100,-100,-74,-75,-74,-74,-49,-43,-49,-44,-76.0,-68,2
395,-100,-87,-48,-81,-71,-100,-100,-73,-72,-73,-73,-43,-43,-46,-48,-75.0,-68,2

In [304]:
region_three = pd.read_csv('Region_Three', delimiter=',')
region_three = region_three.drop(['ID'], axis=1)
region_three

,Abyusif,abram Gad,STUDBME2,BMES_Secrelary,ESP32_One,Saeed,Sbme-Staff,CMP LAB1,CMP LAB2,CMP LAB3,CMP LAB4,CMP_LAB1,CMP_LAB2,CMP_LAB3,CMP_LAB4,Lab-admin,RehabLab,label
0,-100,-83,-41,-100,-85.686,-100,-100,-72,-66,-61,-61,-59,-58,-56,-56,-100,-100,3
1,-100,-100,-32,-100,-85.686,-100,-100,-63,-100,-66,-62,-62,-62,-61,-100,-100,-100,3
2,-100,-100,-44,-100,-85.686,-100,-100,-72,-62,-100,-66,-49,-54,-51,-55,-100,-100,3
3,-100,-73,-36,-76,-85.686,-100,-100,-62,-62,-63,-59,-64,-62,-62,-100,-100,-100,3
4,-86,-100,-42,-76,-85.686,-100,-100,-100,-66,-65,-64,-73,-65,-64,-64,-100,-100,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,-77,-75,-51,-75,-78.000,-100,-100,-61,-60,-61,-62,-58,-56,-58,-59,-100,-100,3
496,-85,-76,-37,-74,-79.000,-100,-100,-61,-61,-60,-60,-66,-63,-64,-64,-100,-100,3
497,-100,-85,-38,-68,-76.000,-100,-100,-58,-59,-60,-62,-61,-62,-60,-60,-100,-100,3
498,-83,-60,-33,-67,-67.000,-100,-100,-60,-60,-63,-61,-66,-64,-66,-66,-100,-100,3
499,-80,-63,-39,-66,-71.000,-100,-100,-60,-62,-61,-61,-59,-58,-61,-60,-100,-100,3

In [305]:
region_four = pd.read_csv('Region_Four', delimiter=',')
region_four

,Abyusif,abram Gad,STUDBME2,BMES_Secrelary,ESP32_One,Saeed,Sbme-Staff,CMP LAB1,CMP LAB2,CMP LAB3,CMP LAB4,CMP_LAB1,CMP_LAB2,CMP_LAB3,CMP_LAB4,Lab-admin,RehabLab,label
0,-71,-63,-65,-80,-75,-71,-100,-100,-100,-100,-100,-72,-73,-71,-70,-86,-100,4
1,-68,-59,-62,-86,-77,-71,-100,-83,-100,-100,-100,-76,-76,-74,-78,-83,-88,4
2,-72,-55,-52,-81,-70,-68,-100,-100,-81,-100,-79,-63,-64,-64,-67,-100,-90,4
3,-82,-54,-50,-82,-71,-69,-100,-78,-100,-76,-78,-63,-67,-66,-65,-82,-87,4
4,-65,-57,-49,-77,-66,-76,-100,-79,-76,-100,-75,-73,-75,-74,-74,-79,-100,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,-71,-57,-54,-74,-62,-66,-82,-80,-79,-77,-79,-79,-79,-77,-76,-83,-92,4
496,-69,-70,-66,-68,-72,-64,-86,-90,-87,-89,-90,-83,-81,-81,-80,-85,-100,4
497,-64,-65,-70,-72,-100,-68,-82,-86,-86,-88,-87,-83,-100,-100,-100,-89,-100,4
498,-66,-63,-69,-71,-72,-75,-80,-100,-90,-91,-92,-83,-81,-80,-83,-84,-100,4
499,-69,-66,-69,-70,-74,-73,-84,-89,-91,-90,-89,-100,-83,-100,-100,-89,-89,4

In [306]:
region_five = pd.read_csv('Region_Five', delimiter=',')
region_five

,Abyusif,abram Gad,STUDBME2,BMES_Secrelary,ESP32_One,Saeed,Sbme-Staff,CMP LAB1,CMP LAB2,CMP LAB3,CMP LAB4,CMP_LAB1,CMP_LAB2,CMP_LAB3,CMP_LAB4,Lab-admin,RehabLab,label
0,-100,-100,-60,-66,-72,-100,-68,-100,-88,-100,-100,-77,-81,-76,-76,-100,-100,5
1,-100,-67,-63,-60,-59,-100,-100,-82,-100,-87,-84,-70,-72,-74,-79,-100,-100,5
2,-100,-69,-64,-67,-59,-87,-74,-100,-79,-79,-80,-72,-73,-72,-73,-100,-100,5
3,-100,-73,-68,-54,-51,-100,-72,-100,-100,-87,-85,-76,-77,-78,-76,-100,-100,5
4,-100,-70,-71,-49,-51,-91,-64,-100,-100,-100,-100,-80,-79,-82,-86,-100,-100,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,-100,-81,-63,-73,-59,-100,-84,-87,-88,-100,-86,-83,-82,-82,-85,-100,-100,5
496,-100,-86,-65,-64,-50,-100,-86,-86,-86,-100,-85,-87,-88,-85,-86,-100,-100,5
497,-100,-75,-67,-53,-49,-91,-87,-87,-91,-89,-100,-80,-82,-84,-81,-100,-100,5
498,-100,-100,-100,-64,-100,-100,-81,-100,-100,-100,-100,-89,-89,-90,-89,-100,-100,5
499,-100,-75,-71,-77,-60,-100,-81,-100,-100,-92,-88,-81,-81,-79,-78,-100,-100,5

In [307]:
region_six = pd.read_csv('Region_Six', delimiter=',')
region_six = region_six.drop(['ID'], axis=1)
region_six

,Abyusif,abram Gad,STUDBME2,BMES_Secrelary,ESP32_One,Saeed,Sbme-Staff,CMP LAB1,CMP LAB2,CMP LAB3,CMP LAB4,CMP_LAB1,CMP_LAB2,CMP_LAB3,CMP_LAB4,Lab-admin,RehabLab,label
0,-65.000000,-57.0,-59,-70,-68,-66.0,-87,-100,-100,-100,-100,-100,-100,-100,-100,-84,-100,6
1,-69.000000,-58.0,-63,-74,-72,-61.0,-87,-78,-100,-100,-77,-100,-100,-100,-100,-100,-100,6
2,-73.000000,-58.0,-73,-86,-85,-55.0,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100,6
3,-68.000000,-66.0,-67,-79,-76,-52.0,-100,-86,-100,-100,-100,-80,-80,-78,-79,-100,-100,6
4,-75.000000,-63.0,-68,-84,-80,-70.0,-100,-79,-100,-100,-100,-81,-76,-100,-100,-100,-100,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,-63.000000,-66.0,-64,-79,-82,-53.0,-100,-84,-100,-100,-84,-83,-86,-100,-84,-100,-100,6
462,-70.611588,-71.0,-64,-100,-100,-50.0,-100,-84,-84,-83,-100,-79,-77,-78,-78,-87,-100,6
463,-68.000000,-72.0,-71,-100,-87,-54.0,-100,-86,-86,-84,-86,-81,-84,-85,-82,-100,-100,6
464,-63.000000,-70.0,-77,-100,-100,-51.0,-100,-87,-100,-86,-100,-85,-100,-100,-100,-100,-100,6
465,-66.000000,-66.0,-67,-100,-72,-58.0,-100,-80,-79,-81,-82,-86,-100,-84,-84,-100,-100,6

In [308]:
region_seven = pd.read_csv('Region_Seven', delimiter=',')
region_seven = region_seven.drop(['ID'], axis=1)
region_seven

,Abyusif,abram Gad,STUDBME2,BMES_Secrelary,ESP32_One,Saeed,Sbme-Staff,CMP LAB1,CMP LAB2,CMP LAB3,CMP LAB4,CMP_LAB1,CMP_LAB2,CMP_LAB3,CMP_LAB4,Lab-admin,RehabLab,label
0,-51,-71,-77,-85,-90,-74,-91,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100,7
1,-66,-83,-83,-100,-88,-76,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100,7
2,-43,-78,-80,-100,-91,-69,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100,7
3,-58,-76,-77,-100,-87,-77,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100,7
4,-50,-79,-81,-100,-87,-74,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,-54,-62,-68,-100,-83,-63,-100,-84,-84,-89,-86,-91,-100,-89,-85,-100,-100,7
495,-53,-61,-100,-100,-81,-66,-100,-84,-86,-87,-86,-82,-81,-83,-82,-100,-100,7
496,-53,-63,-100,-89,-86,-64,-100,-84,-84,-100,-83,-79,-77,-76,-79,-100,-100,7
497,-54,-62,-73,-100,-100,-61,-100,-85,-85,-86,-84,-76,-76,-78,-77,-100,-100,7
498,-59,-62,-72,-100,-80,-70,-100,-100,-88,-85,-100,-79,-78,-77,-77,-100,-100,7

In [309]:
data_set = pd.concat([region_one, region_two, region_three, region_seven, region_five, region_six, region_four], ignore_index=True)
print(data_set)

      Abyusif  abram Gad  STUDBME2  BMES_Secrelary  ESP32_One  Saeed  \
0      -100.0     -100.0       -55             -76      -81.0 -100.0
1      -100.0     -100.0       -57             -71      -68.0 -100.0
2      -100.0     -100.0       -52             -69      -70.0 -100.0
3      -100.0     -100.0       -54             -72      -69.0 -100.0
4      -100.0     -100.0       -50             -71      -66.0 -100.0
...       ...        ...       ...             ...        ...    ...
3356    -71.0      -57.0       -54             -74      -62.0  -66.0
3357    -69.0      -70.0       -66             -68      -72.0  -64.0
3358    -64.0      -65.0       -70             -72     -100.0  -68.0
3359    -66.0      -63.0       -69             -71      -72.0  -75.0
3360    -69.0      -66.0       -69             -70      -74.0  -73.0

      Sbme-Staff  CMP LAB1  CMP LAB2  CMP LAB3  CMP LAB4  CMP_LAB1  CMP_LAB2  \
0           -100       -69       -68       -69       -67       -55       -56
1           -100       -65       -69       -69       -69       -49       -48
2           -100       -61       -60       -62       -61       -54       -56
3           -100       -60       -63       -62      -100       -44       -45
4           -100       -58       -58       -59       -60       -44       -45
...          ...       ...       ...       ...       ...       ...       ...
3356         -82       -80       -79       -77       -79       -79       -79
3357         -86       -90       -87       -89       -90       -83       -81
3358         -82       -86       -86       -88       -87       -83      -100
3359         -80      -100       -90       -91       -92       -83       -81
3360         -84       -89       -91       -90       -89      -100       -83

      CMP_LAB3  CMP_LAB4  Lab-admin  RehabLab  label
0          -55       -55     -76.09     -69.0      1
1          -49       -48     -73.00     -69.0      1
2          -52       -52     -72.00     -66.0      1
3          -42       -41     -76.09     -67.0      1
4          -45       -45     -71.00     -59.0      1
...        ...       ...        ...       ...    ...
3356       -77       -76     -83.00     -92.0      4
3357       -81       -80     -85.00    -100.0      4
3358      -100      -100     -89.00    -100.0      4
3359       -80       -83     -84.00    -100.0      4
3360      -100      -100     -89.00     -89.0      4

[3361 rows x 18 columns]

In [310]:
features = data_set.drop(['label'], axis=1)
target = data_set['label']
print(features)

      Abyusif  abram Gad  STUDBME2  BMES_Secrelary  ESP32_One  Saeed  \
0      -100.0     -100.0       -55             -76      -81.0 -100.0
1      -100.0     -100.0       -57             -71      -68.0 -100.0
2      -100.0     -100.0       -52             -69      -70.0 -100.0
3      -100.0     -100.0       -54             -72      -69.0 -100.0
4      -100.0     -100.0       -50             -71      -66.0 -100.0
...       ...        ...       ...             ...        ...    ...
3356    -71.0      -57.0       -54             -74      -62.0  -66.0
3357    -69.0      -70.0       -66             -68      -72.0  -64.0
3358    -64.0      -65.0       -70             -72     -100.0  -68.0
3359    -66.0      -63.0       -69             -71      -72.0  -75.0
3360    -69.0      -66.0       -69             -70      -74.0  -73.0

      Sbme-Staff  CMP LAB1  CMP LAB2  CMP LAB3  CMP LAB4  CMP_LAB1  CMP_LAB2  \
0           -100       -69       -68       -69       -67       -55       -56
1           -100       -65       -69       -69       -69       -49       -48
2           -100       -61       -60       -62       -61       -54       -56
3           -100       -60       -63       -62      -100       -44       -45
4           -100       -58       -58       -59       -60       -44       -45
...          ...       ...       ...       ...       ...       ...       ...
3356         -82       -80       -79       -77       -79       -79       -79
3357         -86       -90       -87       -89       -90       -83       -81
3358         -82       -86       -86       -88       -87       -83      -100
3359         -80      -100       -90       -91       -92       -83       -81
3360         -84       -89       -91       -90       -89      -100       -83

      CMP_LAB3  CMP_LAB4  Lab-admin  RehabLab
0          -55       -55     -76.09     -69.0
1          -49       -48     -73.00     -69.0
2          -52       -52     -72.00     -66.0
3          -42       -41     -76.09     -67.0
4          -45       -45     -71.00     -59.0
...        ...       ...        ...       ...
3356       -77       -76     -83.00     -92.0
3357       -81       -80     -85.00    -100.0
3358      -100      -100     -89.00    -100.0
3359       -80       -83     -84.00    -100.0
3360      -100      -100     -89.00     -89.0

[3361 rows x 17 columns]

In [311]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3,random_state=109)

In [312]:
SVM = svm.SVC(kernel='rbf', gamma=0.001)
SVM.fit(X_train, y_train)
y_pred = SVM.predict(X_test)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.977205153617443

In [313]:
KNN = KNeighborsClassifier(n_neighbors=13)
KNN.fit(X_train, y_train)
y_pred = KNN.predict(X_test)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9524281466798811

In [314]:
mlp = MLPClassifier(activation='relu', hidden_layer_sizes=(5,5,5), max_iter=3000, random_state=0)
mlp.fit(X_train, y_train)
y_pred = mlp.predict(X_test)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7888999008919723

In [315]:
rf = RandomForestClassifier(n_estimators=200)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.981169474727453

In [316]:
from micromlgen import port

In [317]:
c_code = port(SVM)  #convert our model

#Let's write it into a .h file
modelFile = open("SVM.h", "w")
modelFile.write(c_code)
modelFile.close()

#Let's print the size of the .h file
import os
SVM_h_size = os.path.getsize("SVM.h")
print(f"Header file, model.h, is {SVM_h_size:,} bytes.")

Header file, model.h, is 275,297 bytes.

In [318]:
c_code = port(rf)  #convert our model

#Let's write it into a .h file
modelFile = open("RF.h", "w")
modelFile.write(c_code)
modelFile.close()

#Let's print the size of the .h file
import os
rf_h_size = os.path.getsize("RF.h")
print(f"Header file, model.h, is {rf_h_size:,} bytes.")

Header file, model.h, is 7,620,079 bytes.